In [2]:
import numpy as np
import pandas as pd

import os
for dirname,_,filenames in os.walk('/Users/anishsoni/Desktop/Movie_Recommendation_System'):
    for filename in filenames:
        print(os.path.join(dirname,filename))

/Users/anishsoni/Desktop/Movie_Recommendation_System/Untitled.ipynb
/Users/anishsoni/Desktop/Movie_Recommendation_System/u.data
/Users/anishsoni/Desktop/Movie_Recommendation_System/.ipynb_checkpoints/Untitled-checkpoint.ipynb

In [6]:
column_names = ['user_id','item_id','rating','timestamp']
df = pd.read_csv('/Users/anishsoni/Desktop/Movie_Recommendation_System/u.data', sep= '\t', names = column_names)

In [7]:
df.head()

   user_id  item_id  rating  timestamp
0        0       50       5  881250949
1        0      172       5  881250949
2        0      133       1  881250949
3      196      242       3  881250949
4      186      302       3  891717742

In [9]:
movie_titles = pd.read_csv("https://storage.googleapis.com/kagglesdsdata/datasets/3936828/6848095/Movie_Id_Titles.txt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20231122%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20231122T152607Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=8bef7dab994088ad9991a1d08b359d4a0922723e6951d92998f8ea6a5b04807fbb7f9f907fe22d59a4aee6b797d82dd4a0bcfe890637b265f35478ef3873020062554520b82034766e5bd8fdaa8bff66fd8e2af75ea66b6038f37e89b99a672409385607513c5d267856500e916627542352e2a9ec5b95757b541b727ef20af4d070f8b644c71fe4d515d0a855a55ad960de2c935c4711772d14a4dfc9550cb9ebd1cf06376bd031c47d4ef72a4d69d819c4a4165b553911be36758aa9f7c29f533ebce80a9915e97d5bf07686ddbbef1d13bca8e2ea5c7eff001924df882221c7fe34c40ae0435e4916679d207cfbc70de4c308e67b7a24b43cca19fecacde3")
movie_titles.head()

   item_id              title
0        1   Toy Story (1995)
1        2   GoldenEye (1995)
2        3  Four Rooms (1995)
3        4  Get Shorty (1995)
4        5     Copycat (1995)

In [10]:
df= pd.merge(df, movie_titles, on='item_id')

In [11]:
df.head()

   user_id  item_id  rating  timestamp             title
0        0       50       5  881250949  Star Wars (1977)
1      290       50       5  880473582  Star Wars (1977)
2       79       50       4  891271545  Star Wars (1977)
3        2       50       5  888552084  Star Wars (1977)
4        8       50       5  879362124  Star Wars (1977)

## Data Visualization

In [12]:
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('white')

In [13]:
%matplotlib inline

In [14]:
df.groupby('title')['rating'].mean().sort_values(ascending = False).head()

title
They Made Me a Criminal (1939)                5.0
Marlene Dietrich: Shadow and Light (1996)     5.0
Saint of Fort Washington, The (1993)          5.0
Someone Else's America (1995)                 5.0
Star Kid (1997)                               5.0
Name: rating, dtype: float64

In [15]:
df.groupby('title')['rating'].count().sort_values(ascending = False).head()

title
Star Wars (1977)             584
Contact (1997)               509
Fargo (1996)                 508
Return of the Jedi (1983)    507
Liar Liar (1997)             485
Name: rating, dtype: int64

In [16]:
ratings = pd.DataFrame(df.groupby('title')['rating'].mean())
ratings.head()

                             rating
title
'Til There Was You (1997)  2.333333
1-900 (1994)               2.600000
101 Dalmatians (1996)      2.908257
12 Angry Men (1957)        4.344000
187 (1997)                 3.024390